services:
  scraper:
    build:
      context: .
      dockerfile: ingestor/scraper/Dockerfile
    volumes:
      - ./ingestor/scraper:/app/ingestor/scraper
    command: python ingestor/scraper/main.py


  builder:
    build:
      context: .
      dockerfile: ingestor/builder/Dockerfile
    volumes:
      - ./ingestor/builder:/app/ingestor/builder
    command: python ingestor/builder/main.py


  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app/web
      - /app/web/node_modules
    ports:
      - "4200:4200"
    command: ng serve --host 0.0.0.0
