services:
  scraper:
    build:
      context: .
      dockerfile: ingestor/scraper/Dockerfile
    volumes:
      - ./ingestor/scraper:/app/ingestor/scraper
    working_dir: /app/ingestor/scraper/
    ports:
      - "${SCRAPER_PORT}:8080"
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8080 --reload

  builder:
    build:
      context: .
      dockerfile: ingestor/builder/Dockerfile
    volumes:
      - ./ingestor/builder:/app/ingestor/builder
    command: python ingestor/builder/main.py
    env_file:
      - .env

  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app/web
      - /app/web/node_modules
      - ./.env:/app/.env
    ports:
      - "${ANGULAR_PORT}:4200"
    command: npm run serve

  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "${KAFKA_PORT}:9094"
