[project]
name = "Crypto-Viz"
version = "0.1.0"
description = "Ingestor : scraper + builder"
authors = [{name = "Max", email = "maxime.durand@epitech.eu"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi",
    "charset-normalizer",
    "idna",
    "pip",
    "requests",
    "setuptools",
    "urllib3",
    "fastapi",
    "uvicorn",
    "python-dotenv",
    "scrapy",
    "twisted",
    "selenium",
    "webdriver-manager",
    "fake-useragent",
    "pydantic",
    "kafka-python",
    "feedparser",
    "pytest",
    "fastapi",
    "typer",
    "pandas",
    "httpx",
    "beautifulsoup4",
    "lxml",
    "backoff",
    "sqlite3"
]


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["ingestor*"]